### ISSUE TITLE
Masterwork non-adept weapons shows it has +3 overall stats

### ISSUE THREAD

**Issue by ELELrnf** [Ice-mourne/Clarity-A-DIM-Companion#15]
![image](https://user-images.githubusercontent.com/104226727/164781212-ce59b4a5-e87a-4d72-99f5-f25b9255f3db.png)
![image](https://user-images.githubusercontent.com/104226727/164781985-866f34d7-630c-49ed-b415-2710cef8afe9.png)

for me, this happens to every non-exotic, non-adept masterwork weapons
it went away when I uninstall this extension, and came back as I install again
I think it was not happen before Witch Queen

**Comment by Ice-mourne** [comment]
fixed
