### ISSUE TITLE
Crafted Enhanced Perks not showing its additional details

### ISSUE THREAD

**Issue by ELELrnf** [Ice-mourne/Clarity-A-DIM-Companion#18]
![image](https://user-images.githubusercontent.com/104226727/174458705-c43a37cb-4c58-4fcb-a8ca-1db06cd8c3e6.png)
Normal weapons showing its details

![image](https://user-images.githubusercontent.com/104226727/174458721-1e924de9-609e-4732-b859-a84601ce56d3.png)
Crafted weapon that has 2 enhanced perk only showing its in-game description

![image](https://user-images.githubusercontent.com/104226727/174458746-e1c22aef-cbcb-4e1f-9241-6b53539c0914.png)
Crafted weapon that has 1 enhanced perk can only show non-enhanced perk's detail, and can't open details for enhanced perk

1st, 2nd perk and all other stuffs working fine for me

**Comment by Ice-mourne** [comment]
We haven't yet added descriptions too enhanced perks they have to be added
separately
We will add them after updates to description editor are complete
