### ISSUE TITLE
Account not found and stats and perk descriptions do not show

### ISSUE THREAD

**Issue by judgcc** [Ice-mourne/Clarity-A-DIM-Companion#2]
Have tried uninstalling Clarity, resetting Bungie.net & DIM site settings, caches and cookies, have relogged my Bungie account, tried with both production DIM and beta DIM, none of these have fixed the issue so far. I am using Chrome.

DIM itself links to my account and inventory normally every time, but when I authorize Clarity to Bungie.net, it always ends up with 'Account not found - The account you're trying to view is not an account linked to your Bungie.net profile' for like half a second before it immediately goes back to DIM's inventory tab. Clarity menu is listed as normal on the top left and can be opened, but the actual stat and perk functionalities of it aren't shown.

Have checked the extension on Chrome and it always seems to be these 2 errors
Uncaught (in promise) TypeError: Cannot read property 'singleInitialItemHash' of undefined
Uncaught TypeError: Cannot read property 'classList' of null

![1](https://user-images.githubusercontent.com/90189632/132206404-3d39998b-2327-4868-8caa-72fe7b0a39b6.png)
![2](https://user-images.githubusercontent.com/90189632/132206537-2f3d5d59-012c-4d35-b02b-0c1c77bee04c.png)
![3](https://user-images.githubusercontent.com/90189632/132206549-7cb63161-65fa-45b7-9320-9a881eb07851.png)

To show that Clarity is installed but not working

![4](https://user-images.githubusercontent.com/90189632/132207086-e047f03e-1b67-48ff-9070-3f61c1535f14.PNG)

I know you're working on this project less now and it's understandable if it takes time, so I just want to know if this is an issue the commits you have been working on recently in the past few days will fix or not, because I have tried to manually replace the newer files over the old ones but it did not work, and other people I know of who also use Clarity have no issues with it right now. Thanks in advance!

**Comment by Ice-mourne** [comment]
Join my discord https://discord.gg/43TPU5ehmP
I work on this project less than before but i still fix bugs as fast as i
can

**Comment by Ice-mourne** [comment]
should be fixed didn't get an answer and its time to close it
