### ISSUE TITLE
Build 1.5.14 doesn't seem to work with DIM beta at all on Firefox

### ISSUE THREAD

**Issue by jacob-long** [Ice-mourne/Clarity-A-DIM-Companion#3]
I think this may be due to a change on DIM's end since 1.5.12 wasn't working either. Haven't checked other browsers/versions.

**Comment by Ice-mourne** [comment]
I know about that it's because change in DIM i will fix it soon it's common problem in 1.6 it will be fixed permanently for current version fix will be automatic no need to update

**Comment by jacob-long** [comment]
Sounds good, thank you for your efforts!

**Comment by Ice-mourne** [comment]
Firefox is no longer officially supported (basically just not going to upload new versions to the firefox store) because their support is awful but I will fix bugs if there will be any 
and a new version is available on other browser stores and manual installation should work
