### ISSUE TITLE
Recent changes to perk display not compatible with Clarity 1.5.12

### ISSUE THREAD

**Issue by dsdsdsdgg** [Ice-mourne/Clarity-A-DIM-Companion#4]
First of all, thank you for this addon. 👍

Do to some changes in how perks are displayed with the latest beta versions, the perks are misaligned and dim will crash when you attempt to change to grid mode.

In list mode:
![image](https://user-images.githubusercontent.com/35578434/138567136-66787f6c-b4c2-4440-a6a5-8c9a0e0d4063.png)

After pressing to change to grid mode:
![image](https://user-images.githubusercontent.com/35578434/138567264-fc50a589-1f97-4e53-8668-f94caf9ae14f.png)
(It's fixed by using Reload App.)

Screenshots taken on v6.87.0.1000793 (beta), and Brave (chrome).

**Comment by Ice-mourne** [comment]
Fixed in 1.6.x also available in chrome store
https://chrome.google.com/webstore/detail/clarity-a-dim-companion/mbhfgfjjllobldiodabdmaoimehdkdjc?hl=en
