### ISSUE TITLE
Expanded exotic perk descriptions break the Compare view when adding new items to that view

### ISSUE THREAD

**Issue by FlaminSarge** [Ice-mourne/Clarity-A-DIM-Companion#5]
When comparing items, if you select another item to add to the Compare view and it has an exotic perk, Clarity expands the exotic perk details in the Compare view:
![image](https://user-images.githubusercontent.com/2764675/143528088-d78251f6-3cc5-4284-a927-7cd3fa16c5dd.png)

This breaks the Compare view when it occurs.
It seems it only occurs for armor.

Repro steps:
1) Click on an item and select 'Compare'.
2) Click on an exotic item that matches that item's class and slot.

**Comment by Ice-mourne** [comment]
Fixed in Chrome store version 
https://chrome.google.com/webstore/detail/clarity-a-dim-companion/mbhfgfjjllobldiodabdmaoimehdkdjc?hl=en

**Comment by FlaminSarge** [comment]
This still seems to be occurring in v1.6.6 on Chrome.

**Comment by Ice-mourne** [comment]
Thx for bringing this up I did upsie and fixed this for weapons and forgot I have to add an exception for armor separately
It's fixed in 1.6.7 on GitHub not sure then will be available in the Chrome store sometimes it takes a while

**Comment by FlaminSarge** [comment]
Seems like it's updated, fixed in 1.6.7. Nice work.

Slightly related, would it be worth making the hover tooltips contain the extra Clarity info for exotics in the Compare view? Potentially only when the icon is clicked, as I am unsure when or where the tooltip loads the current text that it contains.
